// Toggle Sidebar
function toggleSidebar() {
    const sidebar = document.getElementById("sidebar");
    sidebar.classList.toggle("collapsed");
  }
  
  // Logout Function
  function logout() {
    // You can add real logout logic here (session clear, redirect etc.)
    alert("You have been logged out!");
    window.location.href = "index.html"; // Redirect to login page
  }
  
  // Open Modal
  function openPetitionModal() {
    document.getElementById("petitionModal").style.display = "block";
  }
  
  // Close Modal
  function closeModal() {
    document.getElementById("petitionModal").style.display = "none";
  }
  
  // Close modal when clicking outside of it
  window.onclick = function (event) {
    const modal = document.getElementById("petitionModal");
    if (event.target === modal) {
      modal.style.display = "none";
    }
  };
  
  // Download table content as PDF
  function downloadAsPDF() {
    // Initialize jsPDF
    const { jsPDF } = window.jspdf;
    const doc = new jsPDF();
  
    // Add title
    doc.setFontSize(18);
    doc.text("Report for Increase Teacher Salaries", 14, 20);
  
    // Get table data
    const table = document.getElementById("petitionTable");
    const tableData = [];
  
    // Extract table content
    for (let i = 0; i < table.rows.length; i++) {
      const row = table.rows[i];
      const rowData = [];
  
      // Push the header (first cell of each row)
      rowData.push(row.cells[0].textContent.trim());
  
      // Push the content (second cell of each row)
      let cellContent = row.cells[1].textContent.trim();
  
      // Replace bullet points with dashes for better formatting
      cellContent = cellContent.replace(/•/g, "-");
  
      rowData.push(cellContent);
      tableData.push(rowData);
    }
  
    // Set table headers
    const headers = [["Field", "Information"]];
  
    // Auto-generate table
    doc.autoTable({
      head: headers,
      body: tableData,
      startY: 30,
      theme: "grid",
      headStyles: {
        fillColor: [75, 58, 255],
        textColor: [255, 255, 255],
        fontStyle: "bold",
      },
      columnStyles: {
        0: { cellWidth: 50 },
      },
      margin: { top: 30 },
      styles: {
        overflow: "linebreak",
        cellPadding: 4,
      },
    });
  
    // Add footer
    const pageCount = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(10);
      doc.setTextColor(100);
      doc.text(
        `Generated by FairVoice | Page ${i} of ${pageCount}`,
        doc.internal.pageSize.getWidth() / 2,
        doc.internal.pageSize.getHeight() - 10,
        { align: "center" }
      );
    }
  
    // Save the PDF
    doc.save("teacher_salary_petition.pdf");
  
    // Show success message
    const modalContent = document.querySelector(".modal-content");
    const successMsg = document.createElement("div");
    successMsg.className = "success-message";
    successMsg.textContent = "PDF downloaded successfully!";
    successMsg.style.color = "#4CAF50";
    successMsg.style.textAlign = "center";
    successMsg.style.padding = "10px";
    successMsg.style.marginTop = "15px";
  
    // Remove any existing success message
    const existingMsg = document.querySelector(".success-message");
    if (existingMsg) {
      existingMsg.remove();
    }
  
    modalContent.appendChild(successMsg);
  
    // Auto-remove the message after 3 seconds
    setTimeout(() => {
      successMsg.remove();
    }, 3000);
  }
  