// Toggle Sidebar
function toggleSidebar() {
  const sidebar = document.getElementById("sidebar");
  sidebar.classList.toggle("collapsed");
}

// Logout Function
function logout() {
  alert("You have been logged out!");
  window.location.href = "../Main_home.html";
}

// Open Modal with Petition Details
function openPetitionModal(data) {
  const modal = document.getElementById("petitionModal");
  modal.style.display = "block";

  document.querySelector(".modal-content h2").textContent = `Report for ${data.title}`;

  const petitionTable = document.getElementById("petitionTable");
  petitionTable.innerHTML = `
    <tr><th>Petition Title</th><td>${data.title}</td></tr>
    <tr><th>Full Name</th><td>${data.name}</td></tr>
    <tr><th>Phone Number</th><td>${data.phone}</td></tr>
    <tr><th>Location</th><td>${data.location}</td></tr>
    <tr><th>Description</th><td>${data.description}</td></tr>
    <tr><th>Uploaded Documents</th><td>
      <ul>
        ${data.documents.map(doc => `<li><a href="${doc.url}" download>${doc.name}</a></li>`).join("")}
      </ul>
    </td></tr>
  `;
}

// Close Modal
function closeModal() {
  document.getElementById("petitionModal").style.display = "none";
}

// Close modal when clicking outside of it
window.onclick = function (event) {
  const modal = document.getElementById("petitionModal");
  if (event.target === modal) {
    modal.style.display = "none";
  }
};

// Download table content as PDF
function downloadAsPDF() {
  const { jsPDF } = window.jspdf;
  const doc = new jsPDF();

  const title = document.querySelector(".modal-content h2").textContent;
  doc.setFontSize(18);
  doc.text(title, 14, 20);

  const table = document.getElementById("petitionTable");
  const tableData = [];

  for (let i = 0; i < table.rows.length; i++) {
    const row = table.rows[i];
    const rowData = [];
    rowData.push(row.cells[0].textContent.trim());
    let cellContent = row.cells[1].textContent.trim();
    cellContent = cellContent.replace(/•/g, "-");
    rowData.push(cellContent);
    tableData.push(rowData);
  }

  const headers = [["Field", "Information"]];

  doc.autoTable({
    head: headers,
    body: tableData,
    startY: 30,
    theme: "grid",
    headStyles: {
      fillColor: [75, 58, 255],
      textColor: [255, 255, 255],
      fontStyle: "bold"
    },
    columnStyles: {
      0: { cellWidth: 60 }
    },
    margin: { top: 30 },
    styles: {
      overflow: "linebreak",
      cellPadding: 4
    }
  });

  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text(
      `Generated by FairVoice | Page ${i} of ${pageCount}`,
      doc.internal.pageSize.getWidth() / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: "center" }
    );
  }

  const filename = title.toLowerCase().replace(/\s+/g, '_') + ".pdf";
  doc.save(filename);

  const modalContent = document.querySelector(".modal-content");
  const successMsg = document.createElement("div");
  successMsg.className = "success-message";
  successMsg.textContent = "PDF downloaded successfully!";
  successMsg.style.color = "#4CAF50";
  successMsg.style.textAlign = "center";
  successMsg.style.padding = "10px";
  successMsg.style.marginTop = "15px";

  const existingMsg = document.querySelector(".success-message");
  if (existingMsg) {
    existingMsg.remove();
  }

  modalContent.appendChild(successMsg);
  setTimeout(() => {
    successMsg.remove();
  }, 3000);
}
